/**
 * gitSuggestions.js
 * Utility to extract or generate git branch names and commit messages.
 * 
 * Rules:
 * - Heading created first based on prompt.
 * - Every branch name MUST start with "feature/"
 * - Every branch slug MUST contain 5 to 9 words separated by hyphens.
 * - Every commit message MUST contain 7 to 18 words total.
 */

const STOP_WORDS = new Set([
  'i', 'want', 'you', 'to', 'check', 'all', 'and', 'the', 'entire', 'for', 'of', 'a', 'an',
  'is', 'are', 'this', 'that', 'with', 'in', 'on', 'at', 'by', 'from', 'as', 'please',
  'would', 'like', 'should', 'be', 'based', 'same', 'comment', 'could', 'which', 'what',
  'kind', 'work', 'here', 'there', 'some', 'any', 'my', 'your', 'our', 'their', 'we',
  'below', 'above', 'was', 'were', 'prompt', 'generated', 'text', 'banner', 'heading'
]);

function extractHeadingWords(text) {
  if (!text || typeof text !== 'string') return [];

  const words = text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, ' ')
    .split(/\s+/)
    .filter((w) => w.length > 1 && !STOP_WORDS.has(w));

  return words;
}

function formatBranchName(rawWords, variantIndex = 0) {
  let baseWords = rawWords.slice(0, 4);
  if (baseWords.length === 0) baseWords = ['optimize', 'codebase', 'performance'];

  const templates = [
    [...baseWords, 'and', 'improve', 'code', 'quality'],
    ['optimize', ...baseWords, 'for', 'better', 'performance'],
    ['refactor', ...baseWords, 'to', 'enhance', 'efficiency'],
  ];

  let selected = templates[variantIndex % templates.length];
  let uniqueWords = [];
  for (const w of selected) {
    if (!uniqueWords.includes(w) || w === 'and' || w === 'to' || w === 'for') {
      uniqueWords.push(w);
    }
  }

  while (uniqueWords.length < 5) {
    uniqueWords.push('enhancement');
  }

  if (uniqueWords.length > 9) {
    uniqueWords = uniqueWords.slice(0, 8);
  }

  return `feature/${uniqueWords.join('-')}`;
}

function formatCommitMessage(scope, rawWords, variantIndex = 0) {
  const topic = rawWords.slice(0, 4).join(' ');
  const templates = [
    `feat(${scope}): ${topic} and improve overall codebase performance and quality`,
    `feat(${scope}): implement ${topic} with performance optimizations and clean architecture`,
    `feat(${scope}): restructure ${topic} to eliminate bottlenecks and enhance code readability`,
  ];

  let msg = templates[variantIndex % templates.length];
  let words = msg.split(/\s+/);

  if (words.length < 7) {
    msg += ' for better maintainability and code performance';
    words = msg.split(/\s+/);
  }

  if (words.length > 18) {
    msg = words.slice(0, 16).join(' ');
  }

  return msg;
}

/**
 * Extracts explicit git branches and commits from LLM output, or dynamically generates
 * suggestions adhering to the 5-9 word branch and 7-18 word commit constraints.
 *
 * @param {string} output - The generated LLM prompt text
 * @param {Object} [inputs] - Optional form inputs ({ taskType, fileName, className, methodName, issue, taskName })
 * @returns {{ branches: string[], commits: string[] }}
 */
export function extractOrGenerateGitSuggestions(output, inputs = {}) {
  if (!output || typeof output !== 'string') {
    return { branches: [], commits: [] };
  }

  const branches = [];
  const commits = [];

  // 1. Try parsing explicit markdown headers if generated by LLM
  const branchSectionMatch = output.match(/###\s*Suggested\s*Git\s*Branches[:\s]*([\s\S]*?)(?=###|$)/i);
  if (branchSectionMatch) {
    const rawLines = branchSectionMatch[1].split('\n');
    for (const line of rawLines) {
      let cleaned = line.replace(/^[\s\-*`>]+|[`\s]+$/g, '').trim();
      if (cleaned) {
        if (!cleaned.startsWith('feature/')) {
          cleaned = 'feature/' + cleaned.replace(/^[^/]+\//, '');
        }
        branches.push(cleaned);
      }
    }
  }

  const commitSectionMatch = output.match(/###\s*Suggested\s*Git\s*Commit\s*Messages[:\s]*([\s\S]*?)(?=###|$)/i);
  if (commitSectionMatch) {
    const rawLines = commitSectionMatch[1].split('\n');
    for (const line of rawLines) {
      const cleaned = line.replace(/^[\s\-*`>]+|[`\s]+$/g, '').trim();
      if (cleaned && cleaned.length > 5) {
        commits.push(cleaned);
      }
    }
  }

  // 2. Fallback / Standardizer: Generate suggestions ensuring branch 5-9 words and commit 7-18 words
  const headingText =
    inputs.issue ||
    inputs.taskName ||
    inputs.taskDesc ||
    inputs.methodName ||
    inputs.className ||
    inputs.fileName ||
    output.split('\n')[0] ||
    'optimize code performance';

  let rawWords = extractHeadingWords(headingText);
  if (rawWords.length === 0) {
    rawWords = ['optimize', 'codebase', 'performance', 'quality'];
  }

  const scopeWords = extractHeadingWords(inputs.fileName || inputs.className || inputs.methodName || 'codebase');
  const scope = scopeWords[0] || 'codebase';

  if (branches.length === 0) {
    branches.push(
      formatBranchName(rawWords, 0),
      formatBranchName(rawWords, 1),
      formatBranchName(rawWords, 2),
    );
  }

  if (commits.length === 0) {
    commits.push(
      formatCommitMessage(scope, rawWords, 0),
      formatCommitMessage(scope, rawWords, 1),
      formatCommitMessage(scope, rawWords, 2),
    );
  }

  // Ensure every branch starts with feature/ and slug has 5-9 words
  const sanitizedBranches = branches.map((b, idx) => {
    let slug = b.replace(/^feature\//i, '').replace(/^[^/]+\//, '');
    let words = slug.split(/[-_\s]+/).filter(Boolean);
    if (words.length < 5 || words.length > 9) {
      return formatBranchName(rawWords, idx);
    }
    return `feature/${words.join('-')}`;
  });

  // Ensure every commit message has 7-18 words
  const sanitizedCommits = commits.map((c, idx) => {
    let words = c.split(/\s+/).filter(Boolean);
    if (words.length < 7 || words.length > 18) {
      return formatCommitMessage(scope, rawWords, idx);
    }
    return c;
  });

  return {
    branches: Array.from(new Set(sanitizedBranches)).slice(0, 3),
    commits: Array.from(new Set(sanitizedCommits)).slice(0, 3),
  };
}
