/**
 * gitSuggestions.js
 * Utility to extract or generate git branch names and commit messages
 * strictly tailored to the specific kind of work being performed.
 */

function slugify(text) {
  if (!text) return '';
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .slice(0, 35)
    .replace(/-$/, '');
}

/**
 * Extracts explicit git branches and commits from LLM output, or dynamically generates
 * work-type specific suggestions based on form inputs / prompt context.
 *
 * @param {string} output - The generated LLM prompt text
 * @param {Object} [inputs] - Optional form inputs ({ taskType, fileName, className, methodName, issue, taskName })
 * @returns {{ branches: string[], commits: string[] }}
 */
export function extractOrGenerateGitSuggestions(output, inputs = {}) {
  if (!output || typeof output !== 'string') {
    return { branches: [], commits: [] };
  }

  const branches = [];
  const commits = [];

  // 1. Try parsing explicit markdown headers if generated by LLM
  const branchSectionMatch = output.match(/###\s*Suggested\s*Git\s*Branches[:\s]*([\s\S]*?)(?=###|$)/i);
  if (branchSectionMatch) {
    const rawLines = branchSectionMatch[1].split('\n');
    for (const line of rawLines) {
      const cleaned = line.replace(/^[\s\-*`>]+|[`\s]+$/g, '').trim();
      if (cleaned && (cleaned.includes('/') || cleaned.includes('-'))) {
        branches.push(cleaned);
      }
    }
  }

  const commitSectionMatch = output.match(/###\s*Suggested\s*Git\s*Commit\s*Messages[:\s]*([\s\S]*?)(?=###|$)/i);
  if (commitSectionMatch) {
    const rawLines = commitSectionMatch[1].split('\n');
    for (const line of rawLines) {
      const cleaned = line.replace(/^[\s\-*`>]+|[`\s]+$/g, '').trim();
      if (cleaned && cleaned.length > 5) {
        commits.push(cleaned);
      }
    }
  }

  // 2. Fallback / Enhancement: Generate smart work-type specific suggestions if none parsed
  if (branches.length === 0 || commits.length === 0) {
    const topicRaw =
      inputs.issue ||
      inputs.taskName ||
      inputs.methodName ||
      inputs.className ||
      inputs.fileName ||
      inputs.taskDesc ||
      output.split('\n')[0] ||
      'code-update';

    const topicSlug = slugify(topicRaw) || 'update-code';
    const rawScope = inputs.fileName || inputs.className || inputs.methodName || 'core';
    const scope = slugify(rawScope).slice(0, 15) || 'core';
    const taskType = (inputs.taskType || '').toLowerCase();
    const desc = topicSlug.replace(/-/g, ' ');

    let b1, b2, b3;
    let c1, c2, c3;

    if (taskType.includes('bug') || taskType.includes('fix')) {
      b1 = `fix/${topicSlug}`;
      b2 = `bugfix/${topicSlug}`;
      b3 = `fix/${scope}-${topicSlug}`;

      c1 = `fix(${scope}): ${desc}`;
      c2 = `fix(${scope}): resolve issue with ${desc}`;
      c3 = `bugfix(${scope}): handle edge case in ${desc}`;
    } else if (taskType.includes('refactor')) {
      b1 = `refactor/${topicSlug}`;
      b2 = `cleanup/${topicSlug}`;
      b3 = `refactor/${scope}-${topicSlug}`;

      c1 = `refactor(${scope}): ${desc}`;
      c2 = `refactor(${scope}): simplify ${desc} logic`;
      c3 = `cleanup(${scope}): restructure ${desc}`;
    } else if (taskType.includes('unit') || taskType.includes('test')) {
      b1 = `test/${topicSlug}`;
      b2 = `testing/${topicSlug}`;
      b3 = `test/${scope}-${topicSlug}`;

      c1 = `test(${scope}): ${desc}`;
      c2 = `test(${scope}): add unit tests for ${desc}`;
      c3 = `test(${scope}): increase test coverage for ${desc}`;
    } else if (taskType.includes('perf') || taskType.includes('performance')) {
      b1 = `perf/${topicSlug}`;
      b2 = `optimize/${topicSlug}`;
      b3 = `perf/${scope}-${topicSlug}`;

      c1 = `perf(${scope}): ${desc}`;
      c2 = `perf(${scope}): optimize performance of ${desc}`;
      c3 = `perf(${scope}): improve speed and memory for ${desc}`;
    } else if (taskType.includes('review') || taskType.includes('code review')) {
      b1 = `review/${topicSlug}`;
      b2 = `audit/${topicSlug}`;
      b3 = `refactor/${topicSlug}`;

      c1 = `docs(${scope}): address code review feedback for ${desc}`;
      c2 = `refactor(${scope}): address code review recommendations`;
      c3 = `chore(${scope}): code review polish for ${desc}`;
    } else {
      // Feature or Default
      b1 = `feature/${topicSlug}`;
      b2 = `feat/${topicSlug}`;
      b3 = `feature/${scope}-${topicSlug}`;

      c1 = `feat(${scope}): ${desc}`;
      c2 = `feat(${scope}): implement ${desc} functionality`;
      c3 = `feat(${scope}): add support for ${desc}`;
    }

    if (branches.length === 0) {
      branches.push(b1, b2, b3);
    }

    if (commits.length === 0) {
      commits.push(c1, c2, c3);
    }
  }

  // Deduplicate and cap to top 3 each
  return {
    branches: Array.from(new Set(branches)).slice(0, 3),
    commits: Array.from(new Set(commits)).slice(0, 3),
  };
}
